dist: xenial 
sudo: required 
language: csharp 
mono: none 
dotnet: 2.2.203 
solution: ToDo.sln

install:
- dotnet restore

script:
- dotnet build
- dotnet test ToDo.UnitTests/ToDo.UnitTests.csproj
- dotnet test ToDo.IntegrationTests/ToDo.IntegrationTests.csproj
- make clean
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
- build-wrapper-linux-x86-64 --out-dir bw-output make all
  # Execute some tests
- make test
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
- sonar-scanner

addons:
  sonarcloud:
    organization: "kiwsan"
    token:
      secure: "b9853b67789447e93b2f16ba9400e6311f5cec2d" # encrypted value of your token
