dist: xenial 
sudo: required 
language: csharp 
mono: none 
dotnet: 2.2.203 
solution: ToDo.sln 

install:
- dotnet restore

script:
- dotnet build
- dotnet test ToDo.UnitTests/ToDo.UnitTests.csproj
- dotnet test ToDo.IntegrationTests/ToDo.IntegrationTests.csproj
