language: csharp
dist: trusty
mono: none
dotnet: 2.2.203 

install:
- dotnet restore

script:
- dotnet build
- dotnet test ToDo.UnitTests/ToDo.UnitTests.csproj
- dotnet test ToDo.IntegrationTests/ToDo.IntegrationTests.csproj
